version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"       # for AMQP protocol
      - "15672:15672"     # for management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:

  
  # --- User Microservice ---
  user_service:
    build:
      context: ./user_service
      dockerfile: Dockerfile.user
    env_file:
      - ./user_service/user.env
    ports:
      - "8001:8000"
    depends_on:
      - localhost

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpass
      POSTGRES_DB: usermanagement
    ports:
      - "5432:5432"
  

  # --- Workflow Microservice ---
  workflow_api:
    build:
      context: ./workflow_api
      dockerfile: Dockerfile.workflow
    env_file:
      - ./workflow_api/workflow.env
    depends_on:
      - localhost
    ports:
      - "8002:8000"

  workflow_db:
    image: postgres:15
    environment:
      POSTGRES_DB: workflowmanagement
      POSTGRES_USER: workflowuser
      POSTGRES_PASSWORD: workflowpass
    ports:
      - "5433:5432"
  
  # --- Tracking Microservice ---
  tracking_service:
    build:
      context: ./tracking_service
      dockerfile: Dockerfile.tracking
    env_file:
      - ./tracking_service/tracking.env
    depends_on:
      - localhost
    ports:
      - "8003:8000"

  tracking_db:
    image: postgres:15
    environment:
      POSTGRES_DB: trackingmanagement
      POSTGRES_USER: trackinguser
      POSTGRES_PASSWORD: trackingpass
    ports:
      - "5433:5432"
  
  # --- Ticket Microservice ---
  ticket_service:
    build:
      context: ./ticket_service
      dockerfile: Dockerfile.ticket
    env_file:
      - ./ticket_service/ticket.env
    ports:
      - "8004:8000"
    depends_on:
      - localhost
  
  ticket_db:
    image: postgres:15
    environment:
      POSTGRES_DB: ticketmanagement
      POSTGRES_USER: ticketuser
      POSTGRES_PASSWORD: ticketpass
    ports:
      - "5433:5432"